"""add_rehab_plan

Revision ID: 1016ff26ee6b
Revises: e054f25f2b80
Create Date: 2026-05-02 18:34:07.487966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db.models


# revision identifiers, used by Alembic.
revision: str = '1016ff26ee6b'
down_revision: Union[str, None] = 'e054f25f2b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rehab_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fev1_liters', sa.Float(), nullable=True),
    sa.Column('fvc_liters', sa.Float(), nullable=True),
    sa.Column('six_mwt_distance', sa.Float(), nullable=True),
    sa.Column('dyspnea_scale', sa.Integer(), nullable=True),
    sa.Column('session_frequency_daily', sa.Integer(), nullable=True),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('intensity_level', sa.String(), nullable=True),
    sa.Column('recommended_exercises', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rehab_plans')
    # ### end Alembic commands ###
