"""Initial migration

Revision ID: 8f27c02c1b30
Revises: 
Create Date: 2026-04-30 23:07:07.718715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f27c02c1b30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('clinician_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_vitals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spo2_resting', sa.Float(), nullable=True),
    sa.Column('hr_resting', sa.Integer(), nullable=True),
    sa.Column('dyspnea_borg', sa.Integer(), nullable=True),
    sa.Column('sputum_score', sa.Integer(), nullable=True),
    sa.Column('fatigue_level', sa.Integer(), nullable=True),
    sa.Column('cough_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'recorded_at')
    )
    op.create_table('gamification_state',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=True),
    sa.Column('longest_streak_days', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('badge_level', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('pft_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('fev1_liters', sa.Float(), nullable=True),
    sa.Column('fev1_pct_predicted', sa.Float(), nullable=True),
    sa.Column('fvc_liters', sa.Float(), nullable=True),
    sa.Column('fvc_pct_predicted', sa.Float(), nullable=True),
    sa.Column('fev1_fvc_ratio', sa.Float(), nullable=True),
    sa.Column('dlco_pct_predicted', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('total_breaths', sa.Integer(), nullable=True),
    sa.Column('good_breath_pct', sa.Float(), nullable=True),
    sa.Column('avg_bpm', sa.Float(), nullable=True),
    sa.Column('avg_depth_score', sa.Float(), nullable=True),
    sa.Column('spo2_min', sa.Float(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('session_terminated_early', sa.Boolean(), nullable=True),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('risk_predictions')
    op.drop_table('pft_results')
    op.drop_table('gamification_state')
    op.drop_table('daily_vitals')
    op.drop_table('patients')
    op.drop_table('clinicians')
    # ### end Alembic commands ###
