"""remove_sputum_score

Revision ID: e054f25f2b80
Revises: 8f27c02c1b30
Create Date: 2026-05-02 18:25:15.984850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e054f25f2b80'
down_revision: Union[str, None] = '8f27c02c1b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_vitals', 'sputum_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_vitals', sa.Column('sputum_score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
